pipeline {
	agent any
	tools {
        go 'go1.17.2'
    }
	environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0 
        GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
    }
	stages {
		stage("Install Dependencies") {
			steps{
				echo 'Installing dependencies'
				sh 'go version'
                sh 'go get -u golang.org/x/lint/golint'
			}
		}
		stage('Build') {
            steps {
                echo 'Compiling and building'
                sh 'go build'
            }
        }
		stage('Test') {
            steps {
                withEnv(["PATH+GO=${GOPATH}/bin"]){
                    echo 'Running vetting'
                    sh 'go vet .'
                    echo 'Running linting'
                    sh 'golint .'                
                }
            }
        }
	}
}


